version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./webroot:/var/www/html  # Path to the Nginx web root
      - ./data/certbot:/etc/letsencrypt  # Mount directory with certificates
      - ./dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - "80:80"
      - "443:443"
    restart: always

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: name
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./wordpress_data:/var/www/html
    depends_on:
      - mariadb
    ports:
      - "8080:80"

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: databasename
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot:/etc/letsencrypt  # Path for storing certificates
      - ./webroot:/var/www/html  # Path for the web root
    entrypoint: "/bin/sh -c 'while :; do sleep 6h; certbot renew; done'"  # Periodic certificate renewal
